#!/bin/sh

echo "[initramfs] Booting..."

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev

# Parse root=
for arg in $(cat /proc/cmdline); do
    case "$arg" in
        root=*) ROOT="${arg#root=}" ;;
    esac
done

[ -z "$ROOT" ] && ROOT="/dev/sda1"
echo "[initramfs] Mounting root $ROOT"
mkdir /mnt
mount -o ro "$ROOT" /mnt || exec sh

echo "[initramfs] Switching to real root..."
exec switch_root /mnt /sbin/init
