name: Build initramfs

on:
  workflow_dispatch:

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check directory
        run: ls -a

      - name: Install dependencies
        run: |
          lsb_release -a
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make gdb
          sudo apt-get install -y texinfo gawk bison sed wget xz-utils
          sudo apt-get install -y python3-dev python3-pip python-is-python3
          sudo pip install pexpect

      - name: Install Kernel Headers
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.7.tar.xz
          tar -xf linux-6.6.7.tar.xz
          make -C linux-6.6.7 headers_install INSTALL_HDR_PATH=$GITHUB_WORKSPACE/kernel-headers

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh clean
        run: ./build.sh clean

      - name: Run build.sh build initramfs
        env:
          KERNEL_HEADERS: ${{ github.workspace }}/kernel-headers/include
        run: ./build.sh build initramfs

      - name: Run ls command
        run: ls -al

      - name: Ensure artifacts directory exists
        run: mkdir -p artifacts

      - name: Copy initramfs.cpio.gz to artifacts/
        run: cp build/initramfs.cpio.gz artifacts/

      # Optionally: Upload as a workflow artifact
      - name: Upload initramfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: initramfs
          path: artifacts/initramfs.cpio.gz

      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: 
          # An explicit key for restoring and saving the cache
          key: 
          # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
          restore-keys: # optional
          # The chunk size used to split up large files during upload, in bytes
          upload-chunk-size: # optional
          # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
          enableCrossOsArchive: # optional, default is false
          # Fail the workflow if cache entry is not found
          fail-on-cache-miss: # optional, default is false
          # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
          lookup-only: # optional, default is false
          # Run the post step to save the cache even if another step before fails
          save-always: # optional, default is false
          
