name: Build initramfs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache sources
      uses: actions/cache@v3
      with:
        path: sources
        key: ${{ runner.os }}-sources-${{ hashFiles('packages/**') }}
        restore-keys: |
          ${{ runner.os }}-sources-

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Create build directory
      run: mkdir -p build
    
    - name: Build initramfs
      run: |
        chmod +x smolpkg scripts/*.sh
        ./smolpkg install initramfs-base busybox --target initramfs
        ./smolpkg mkinitramfsimg --target initramfs

    - name: Upload initramfs artifact
      uses: actions/upload-artifact@v4
      with:
        name: initramfs
        path: build/initramfs.cpio.gz