name: Run build.sh and Extract Value

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh
        run: ./build.sh

      - name: Run ls command
        run: ls -al
