name: Run build.sh and Extract Value

on:
  workflow_dispatch:

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh clean
        run: ./build.sh clean
        
      - name: Run build.sh build initramfs
        run: ./build.sh build initramfs

      - name: Run ls command
        run: ls -al