name: Run build.sh

on:
  workflow_dispatch:

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          lsb_release -a
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make gdb
          sudo apt-get install -y texinfo gawk bison sed wget xz-utils
          sudo apt-get install -y python3-dev python3-pip python-is-python3
          sudo pip install pexpect

      - name: Install Kernel Headers
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.7.tar.xz
          tar -xf linux-6.6.7.tar.xz
          make -C linux-6.6.7 headers_install INSTALL_HDR_PATH=$GITHUB_WORKSPACE/kernel-headers

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh clean
        run: ./build.sh clean

      - name: Run build.sh build initramfs
        env:
          KERNEL_HEADERS: ${{ github.workspace }}/kernel-headers/include
        run: ./build.sh build initramfs

      - name: Run ls command
        run: ls -al
