name: Run build.sh

on:
  workflow_dispatch:

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          lsb_release -a
          sudo apt-get update
          sudo apt-get install -y build-essential linux-libc-dev linux-headers-$(uname -r) linux-headers-generic
          sudo apt-get install -y gcc make gdb
          sudo apt-get install -y texinfo gawk bison sed
          sudo apt-get install -y python3-dev python3-pip python-is-python3

      - name: ls /usr/include
        run: ls -a /usr/include

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh clean
        run: ./build.sh clean
        
      - name: Run build.sh build initramfs
        run: ./build.sh build initramfs

      - name: Run ls command
        run: ls -al
