name: Build rootfs

on:
  workflow_dispatch:

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Restore cache for "sources" directory
      - name: Restore sources cache
        uses: actions/cache@v4
        with:
          path: sources
          key: sources-${{ runner.os }}-${{ hashFiles('**/sources/**') }}
          restore-keys: |
            sources-${{ runner.os }}-

      - name: check directory
        run: ls -a

      - name: Install dependencies
        run: |
          lsb_release -a
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make gdb
          sudo apt-get install -y texinfo gawk bison sed wget xz-utils
          sudo apt-get install -y python3-dev python3-pip python-is-python3
          sudo pip install pexpect

      - name: Install Kernel Headers
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.7.tar.xz
          tar -xf linux-6.6.7.tar.xz
          make -C linux-6.6.7 headers_install INSTALL_HDR_PATH=$GITHUB_WORKSPACE/kernel-headers

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh clean
        run: ./build.sh clean

      - name: Run build.sh build rootfs
        env:
          KERNEL_HEADERS: ${{ github.workspace }}/kernel-headers/include
        run: ./build.sh build rootfs

      - name: Run ls command
        run: ls -al

      - name: Ensure artifacts directory exists
        run: mkdir -p artifacts

      - name: Copy rootfs.img to artifacts/
        run: cp build/rootfs.img artifacts/

      # Optionally: Upload as a workflow artifact
      - name: Upload initramfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: initramfs
          path: artifacts/initramfs.cpio.gz

      - name: check directory again
        run: ls -a
          
